name: .NET Build and Test

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # Script personalizado: Restaurar dependências
      - name: Restaurar dependências
        run: dotnet restore github4women/github4women.csproj

      # Script personalizado: Compilar a aplicação
      - name: Compilar aplicação
        run: dotnet build github4women/github4women.csproj --no-restore

      # Script personalizado: Rodar testes
      - name: Executar testes
        run: dotnet test github4women/github4women.csproj --no-build --verbosity normal
