name: .NET Build and Test

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependências
        run: dotnet restore
        working-directory: github4women

      - name: Compilar aplicação
        run: dotnet build --no-restore
        working-directory: github4women

      - name: Executar testes
        run: dotnet test --no-build --verbosity normal
        working-directory: github4women
